---
title: "Good Plot"
author: "Brandon"
date: "3/11/2022"
output: 
  html_document:
    TOC: TRUE
    TOC_FLOAT: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../Output/")
```

## Intro
```{r}
library(tidyverse)
library(here)
library(mapproj)
library(maps)
library(mapdata)
```

## Dataset

```{r, echo=FALSE}
stations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')
View(stations)
```

## Data Analysis
```{r}
California<-map_data("state", region = "california") # Map of California 

Fuel<-stations%>%
  filter(STATE == "CA", # Filtering data and selecting columns
         FUEL_TYPE_CODE == "CNG")%>%
  select(LONGITUDE,
         LATITUDE,
         FUEL_TYPE_CODE,
         CITY)
View(Fuel)
```

## Mapping 
```{r Good1}
ggplot()+
  geom_polygon(data = California, #Setting up the polygon map with easy to see colors
               aes(x = long,
                   y = lat),
               fill = "blue",
               color = "black")+
  geom_point(data = Fuel, #Setting the points on the map to be seen
             aes(x = LONGITUDE,
                 y = LATITUDE,
                 color = FUEL_TYPE_CODE))+
  coord_fixed()+ # fixing coordinates
  labs(title = "Environmentally Friendly Fuel Stations in California", # labeling actually appropriate titles
       x = "Longitude",
       y = "Latitude",
       color = "Fuel Type Code",
       caption = "Data from Week 6 Tidy Tuesdays Fueling Stations")+
  theme(plot.title = element_text(hjust = 0.5), # themes that actually help the image
        panel.border = element_rect(fill = NA,
                                    color = "black"))+
  scale_color_manual(values = "black") 
```
