---
title: "Week 13 Lab"
author: "Brandon"
date: "5/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(here)
library(tidyverse)
```

## Load Data
```{r}
pooldata<-read_csv(here("Week_13", "Data", "homework","TP1.csv"))
pathway<-here("Week_13", "Data", "homework")   # file path
```

## Data Analysis Looping
```{r, map}
poolfiles<-dir(path = pathway, pattern = ".csv")
pooldata0<-data.frame(matrix(ncol = 5, nrow = length(poolfiles)))
View(pooldata0)

colnames(pooldata0) <- c("filename", 
                         "mean_light", 
                         "mean_temp", 
                         "sd_light",
                         "sd_temp")
for (i in 1:length(poolfiles)) {  # loop 
  poolmain <- read_csv(paste0(pathway, "/", poolfiles[i])) # read in files
  pooldata0$filename[i] <- poolfiles[i] # add file names 
  pooldata0$mean_temp[i] <- mean(poolmain$Intensity.lux, na.rm = TRUE) # calculate light mean 
  pooldata0$mean_light[i] <- mean(poolmain$Temp.C, na.rm = TRUE) # calculate temp mean
  pooldata0$sd_temp[i] <- sd(poolmain$Intensity.lux, na.rm = TRUE) # calculate light standard deviation 
  pooldata0$sd_light[i] <- sd(poolmain$Temp.C, na.rm = TRUE) # calculate temp standard deviation 
}
head(pooldata0)
```

## Data Analysis Map
```{r}
poolfilesmap<- dir(path = pathway, pattern = ".csv", full.names = TRUE)

pooldatamap <- poolfilesmap %>%
  set_names() %>%                                                
  map_df(read_csv, .id = "filename") %>%                          
  group_by(filename) %>%                                          
  summarise(mean_light = mean(Intensity.lux, na.rm = TRUE), # calculate light mean
            mean_temp = mean(Temp.C, na.rm = TRUE), # calculate temp mean 
            sd_light = sd(Intensity.lux, na.rm = TRUE), # calculate light standard deviation
            sd_temp = sd(Temp.C, na.rm = TRUE)) # calculate temp standard deviation
pooldatamap
```

